language: c

os:
  - linux
  - osx
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install -y rpm
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - make test
  - cpack
